# Generated by Django 4.2.7 on 2023-12-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('roles_and_responsibillities', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='jobapp.jobposts')),
            ],
        ),
    ]
