# Generated by Django 4.2.7 on 2023-12-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_submit_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='jobtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='jobapp.jobposts'),
            preserve_default=False,
        ),
    ]
