# Generated by Django 4.2.7 on 2023-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_submit_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='addpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('post_type', models.CharField(max_length=120)),
                ('post_title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
