# Generated by Django 4.2.7 on 2023-12-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_addpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='userimg'),
        ),
    ]
