# Generated by Django 4.2.7 on 2023-12-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
