# Generated by Django 4.2.7 on 2023-12-27 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0012_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='likes',
            field=models.ManyToManyField(related_name='postlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
